# Á fazer
* Pré processamento para teste dos modelos

# Bibliotecas e leitura dos dados:

In [1]:
#importanto bibliotecas

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model, preprocessing
import statsmodels.api as sm
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Leitura dos CSVs a partir das colunas importantes retiradas do dicionario:

In [25]:
colunas_treino=['NU_INSCRICAO','CO_UF_RESIDENCIA', 'NU_IDADE', 'TP_SEXO', 'TP_ESTADO_CIVIL',
       'TP_COR_RACA', 'TP_NACIONALIDADE', 'CO_UF_NASCIMENTO',
       'TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU', 'TP_ESCOLA', 'TP_ENSINO',
       'IN_TREINEIRO', 'CO_UF_ESC', 'TP_DEPENDENCIA_ADM_ESC',
       'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC', 'IN_BAIXA_VISAO',
       'IN_CEGUEIRA', 'IN_SURDEZ', 'IN_DEFICIENCIA_AUDITIVA',
       'IN_SURDO_CEGUEIRA', 'IN_DEFICIENCIA_FISICA', 'IN_DEFICIENCIA_MENTAL',
       'IN_DEFICIT_ATENCAO', 'IN_DISLEXIA', 'IN_DISCALCULIA', 'IN_AUTISMO',
       'IN_VISAO_MONOCULAR', 'IN_OUTRA_DEF', 'IN_GESTANTE', 'IN_LACTANTE',
       'IN_IDOSO', 'IN_ESTUDA_CLASSE_HOSPITALAR', 'IN_SEM_RECURSO',
       'IN_BRAILLE', 'IN_AMPLIADA_24', 'IN_AMPLIADA_18', 'IN_LEDOR',
       'IN_ACESSO', 'IN_TRANSCRICAO', 'IN_LIBRAS', 'IN_TEMPO_ADICIONAL',
       'IN_LEITURA_LABIAL', 'IN_MESA_CADEIRA_RODAS',
       'IN_MESA_CADEIRA_SEPARADA', 'IN_APOIO_PERNA', 'IN_GUIA_INTERPRETE',
       'IN_COMPUTADOR', 'IN_CADEIRA_ESPECIAL', 'IN_CADEIRA_CANHOTO',
       'IN_CADEIRA_ACOLCHOADA', 'IN_PROVA_DEITADO', 'IN_MOBILIARIO_OBESO',
       'IN_LAMINA_OVERLAY', 'IN_PROTETOR_AURICULAR', 'IN_MEDIDOR_GLICOSE',
       'IN_MAQUINA_BRAILE', 'IN_SOROBAN', 'IN_MARCA_PASSO', 'IN_SONDA',
       'IN_MEDICAMENTOS', 'IN_SALA_INDIVIDUAL', 'IN_SALA_ESPECIAL',
       'IN_SALA_ACOMPANHANTE', 'IN_MOBILIARIO_ESPECIFICO',
       'IN_MATERIAL_ESPECIFICO', 'IN_NOME_SOCIAL', 'CO_MUNICIPIO_PROVA',
       'CO_UF_PROVA', 'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC',
       'TP_PRESENCA_MT', 'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC',
       'NU_NOTA_MT', 'TP_LINGUA', 'TP_STATUS_REDACAO', 'NU_NOTA_REDACAO']

In [21]:
colunas_teste=['NU_INSCRICAO','CO_UF_RESIDENCIA', 'NU_IDADE', 'TP_SEXO', 'TP_ESTADO_CIVIL',
       'TP_COR_RACA', 'TP_NACIONALIDADE', 'CO_UF_NASCIMENTO',
       'TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU', 'TP_ESCOLA', 'TP_ENSINO',
       'IN_TREINEIRO', 'CO_UF_ESC', 'TP_DEPENDENCIA_ADM_ESC',
       'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC', 'IN_BAIXA_VISAO',
       'IN_CEGUEIRA', 'IN_SURDEZ', 'IN_DEFICIENCIA_AUDITIVA',
       'IN_SURDO_CEGUEIRA', 'IN_DEFICIENCIA_FISICA', 'IN_DEFICIENCIA_MENTAL',
       'IN_DEFICIT_ATENCAO', 'IN_DISLEXIA', 'IN_DISCALCULIA', 'IN_AUTISMO',
       'IN_VISAO_MONOCULAR', 'IN_OUTRA_DEF', 'IN_GESTANTE', 'IN_LACTANTE',
       'IN_IDOSO', 'IN_ESTUDA_CLASSE_HOSPITALAR', 'IN_SEM_RECURSO',
       'IN_BRAILLE', 'IN_AMPLIADA_24', 'IN_AMPLIADA_18', 'IN_LEDOR',
       'IN_ACESSO', 'IN_TRANSCRICAO', 'IN_LIBRAS', 'IN_TEMPO_ADICIONAL',
       'IN_LEITURA_LABIAL', 'IN_MESA_CADEIRA_RODAS',
       'IN_MESA_CADEIRA_SEPARADA', 'IN_APOIO_PERNA', 'IN_GUIA_INTERPRETE',
       'IN_COMPUTADOR', 'IN_CADEIRA_ESPECIAL', 'IN_CADEIRA_CANHOTO',
       'IN_CADEIRA_ACOLCHOADA', 'IN_PROVA_DEITADO', 'IN_MOBILIARIO_OBESO',
       'IN_LAMINA_OVERLAY', 'IN_PROTETOR_AURICULAR', 'IN_MEDIDOR_GLICOSE',
       'IN_MAQUINA_BRAILE', 'IN_SOROBAN', 'IN_MARCA_PASSO', 'IN_SONDA',
       'IN_MEDICAMENTOS', 'IN_SALA_INDIVIDUAL', 'IN_SALA_ESPECIAL',
       'IN_SALA_ACOMPANHANTE', 'IN_MOBILIARIO_ESPECIFICO',
       'IN_MATERIAL_ESPECIFICO', 'IN_NOME_SOCIAL', 'CO_MUNICIPIO_PROVA',
       'CO_UF_PROVA', 'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC',
       'TP_PRESENCA_MT','TP_LINGUA', 'TP_STATUS_REDACAO']

In [23]:
test = pd.read_csv("test.csv", usecols=colunas_teste)
test.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1783345 entries, 0 to 1783344
Data columns (total 76 columns):
 #   Column                       Dtype
---  ------                       -----
 0   NU_INSCRICAO                 object
 1   CO_UF_RESIDENCIA             int64
 2   NU_IDADE                     float64
 3   TP_SEXO                      object
 4   TP_ESTADO_CIVIL              int64
 5   TP_COR_RACA                  int64
 6   TP_NACIONALIDADE             int64
 7   CO_UF_NASCIMENTO             float64
 8   TP_ST_CONCLUSAO              int64
 9   TP_ANO_CONCLUIU              int64
 10  TP_ESCOLA                    int64
 11  TP_ENSINO                    float64
 12  IN_TREINEIRO                 int64
 13  CO_UF_ESC                    float64
 14  TP_DEPENDENCIA_ADM_ESC       float64
 15  TP_LOCALIZACAO_ESC           float64
 16  TP_SIT_FUNC_ESC              float64
 17  IN_BAIXA_VISAO               int64
 18  IN_CEGUEIRA                  int64
 19  IN_SURDEZ                    int64
 20  IN_DEFICIENCIA_AUDITIVA      int64
 21  IN_SURDO_CEGUEIRA            int64
 22  IN_DEFICIENCIA_FISICA        int64
 23  IN_DEFICIENCIA_MENTAL        int64
 24  IN_DEFICIT_ATENCAO           int64
 25  IN_DISLEXIA                  int64
 26  IN_DISCALCULIA               int64
 27  IN_AUTISMO                   int64
 28  IN_VISAO_MONOCULAR           int64
 29  IN_OUTRA_DEF                 int64
 30  IN_GESTANTE                  int64
 31  IN_LACTANTE                  int64
 32  IN_IDOSO                     int64
 33  IN_ESTUDA_CLASSE_HOSPITALAR  int64
 34  IN_SEM_RECURSO               int64
 35  IN_BRAILLE                   int64
 36  IN_AMPLIADA_24               int64
 37  IN_AMPLIADA_18               int64
 38  IN_LEDOR                     int64
 39  IN_ACESSO                    int64
 40  IN_TRANSCRICAO               int64
 41  IN_LIBRAS                    int64
 42  IN_TEMPO_ADICIONAL           int64
 43  IN_LEITURA_LABIAL            int64
 44  IN_MESA_CADEIRA_RODAS        int64
 45  IN_MESA_CADEIRA_SEPARADA     int64
 46  IN_APOIO_PERNA               int64
 47  IN_GUIA_INTERPRETE           int64
 48  IN_COMPUTADOR                int64
 49  IN_CADEIRA_ESPECIAL          int64
 50  IN_CADEIRA_CANHOTO           int64
 51  IN_CADEIRA_ACOLCHOADA        int64
 52  IN_PROVA_DEITADO             int64
 53  IN_MOBILIARIO_OBESO          int64
 54  IN_LAMINA_OVERLAY            int64
 55  IN_PROTETOR_AURICULAR        int64
 56  IN_MEDIDOR_GLICOSE           int64
 57  IN_MAQUINA_BRAILE            int64
 58  IN_SOROBAN                   int64
 59  IN_MARCA_PASSO               int64
 60  IN_SONDA                     int64
 61  IN_MEDICAMENTOS              int64
 62  IN_SALA_INDIVIDUAL           int64
 63  IN_SALA_ESPECIAL             int64
 64  IN_SALA_ACOMPANHANTE         int64
 65  IN_MOBILIARIO_ESPECIFICO     int64
 66  IN_MATERIAL_ESPECIFICO       int64
 67  IN_NOME_SOCIAL               int64
 68  CO_MUNICIPIO_PROVA           int64
 69  CO_UF_PROVA                  int64
 70  TP_PRESENCA_CN               int64
 71  TP_PRESENCA_CH               int64
 72  TP_PRESENCA_LC               int64
 73  TP_PRESENCA_MT               int64
 74  TP_LINGUA                    int64
 75  TP_STATUS_REDACAO            float64
dtypes: float64(8), int64(66), object(2)
memory usage: 1.2 GB

In [26]:
train = pd.read_csv("train.csv", usecols=colunas_treino)
train.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3311925 entries, 0 to 3311924
Data columns (total 81 columns):
 #   Column                       Dtype
---  ------                       -----
 0   NU_INSCRICAO                 object
 1   CO_UF_RESIDENCIA             int64
 2   NU_IDADE                     float64
 3   TP_SEXO                      object
 4   TP_ESTADO_CIVIL              int64
 5   TP_COR_RACA                  int64
 6   TP_NACIONALIDADE             int64
 7   CO_UF_NASCIMENTO             float64
 8   TP_ST_CONCLUSAO              int64
 9   TP_ANO_CONCLUIU              int64
 10  TP_ESCOLA                    int64
 11  TP_ENSINO                    float64
 12  IN_TREINEIRO                 int64
 13  CO_UF_ESC                    float64
 14  TP_DEPENDENCIA_ADM_ESC       float64
 15  TP_LOCALIZACAO_ESC           float64
 16  TP_SIT_FUNC_ESC              float64
 17  IN_BAIXA_VISAO               int64
 18  IN_CEGUEIRA                  int64
 19  IN_SURDEZ                    int64
 20  IN_DEFICIENCIA_AUDITIVA      int64
 21  IN_SURDO_CEGUEIRA            int64
 22  IN_DEFICIENCIA_FISICA        int64
 23  IN_DEFICIENCIA_MENTAL        int64
 24  IN_DEFICIT_ATENCAO           int64
 25  IN_DISLEXIA                  int64
 26  IN_DISCALCULIA               int64
 27  IN_AUTISMO                   int64
 28  IN_VISAO_MONOCULAR           int64
 29  IN_OUTRA_DEF                 int64
 30  IN_GESTANTE                  int64
 31  IN_LACTANTE                  int64
 32  IN_IDOSO                     int64
 33  IN_ESTUDA_CLASSE_HOSPITALAR  int64
 34  IN_SEM_RECURSO               int64
 35  IN_BRAILLE                   int64
 36  IN_AMPLIADA_24               int64
 37  IN_AMPLIADA_18               int64
 38  IN_LEDOR                     int64
 39  IN_ACESSO                    int64
 40  IN_TRANSCRICAO               int64
 41  IN_LIBRAS                    int64
 42  IN_TEMPO_ADICIONAL           int64
 43  IN_LEITURA_LABIAL            int64
 44  IN_MESA_CADEIRA_RODAS        int64
 45  IN_MESA_CADEIRA_SEPARADA     int64
 46  IN_APOIO_PERNA               int64
 47  IN_GUIA_INTERPRETE           int64
 48  IN_COMPUTADOR                int64
 49  IN_CADEIRA_ESPECIAL          int64
 50  IN_CADEIRA_CANHOTO           int64
 51  IN_CADEIRA_ACOLCHOADA        int64
 52  IN_PROVA_DEITADO             int64
 53  IN_MOBILIARIO_OBESO          int64
 54  IN_LAMINA_OVERLAY            int64
 55  IN_PROTETOR_AURICULAR        int64
 56  IN_MEDIDOR_GLICOSE           int64
 57  IN_MAQUINA_BRAILE            int64
 58  IN_SOROBAN                   int64
 59  IN_MARCA_PASSO               int64
 60  IN_SONDA                     int64
 61  IN_MEDICAMENTOS              int64
 62  IN_SALA_INDIVIDUAL           int64
 63  IN_SALA_ESPECIAL             int64
 64  IN_SALA_ACOMPANHANTE         int64
 65  IN_MOBILIARIO_ESPECIFICO     int64
 66  IN_MATERIAL_ESPECIFICO       int64
 67  IN_NOME_SOCIAL               int64
 68  CO_MUNICIPIO_PROVA           int64
 69  CO_UF_PROVA                  int64
 70  TP_PRESENCA_CN               int64
 71  TP_PRESENCA_CH               int64
 72  TP_PRESENCA_LC               int64
 73  TP_PRESENCA_MT               int64
 74  NU_NOTA_CN                   float64
 75  NU_NOTA_CH                   float64
 76  NU_NOTA_LC                   float64
 77  NU_NOTA_MT                   float64
 78  TP_LINGUA                    int64
 79  TP_STATUS_REDACAO            float64
 80  NU_NOTA_REDACAO              float64
dtypes: float64(13), int64(66), object(2)
memory usage: 2.4 GB

Salvando coluna de inscriçao antes de dropar:

In [38]:
out = train['NU_INSCRICAO']
train=train.drop(columns=['NU_INSCRICAO'])
out.head()

0    d7e73c5f-2db8-4089-9bee-d3a0e045f87f
1    668bf6e4-ddf7-4810-b31e-7d325e36de4d
2    951e80d6-ac9b-4ff2-8130-fcbc8ac78b16
3    baf409f9-ddc6-4e82-9a4b-b64b579cd105
4    9fd415ac-3421-44ce-810e-599545c3c025
Name: NU_INSCRICAO, dtype: object

In [39]:
train.head()

,CO_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,CO_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_REDACAO
0,11,31.0,F,0,1,1,32.0,1,10,1,...,1,1,1,426.5,487.4,530.9,415.3,1,1.0,680.0
1,31,23.0,F,1,3,1,31.0,1,3,1,...,1,1,1,463.0,452.3,456.6,407.2,0,1.0,520.0
2,31,17.0,M,0,3,1,31.0,2,0,2,...,1,1,1,381.7,474.4,530.6,622.8,0,1.0,600.0
3,25,16.0,M,1,1,1,25.0,3,0,1,...,1,1,1,426.7,343.9,444.2,507.0,1,1.0,660.0
4,23,19.0,M,1,1,1,23.0,1,1,1,...,1,1,1,623.7,609.1,637.1,805.3,0,1.0,840.0

In [40]:
train = pd.concat([train, pd.get_dummies(train['TP_SEXO'], drop_first=True)], axis=1)
train = train.drop(columns=['TP_SEXO'])

In [41]:
test = pd.concat([test, pd.get_dummies(test['TP_SEXO'], drop_first=True)], axis=1)
test = test.drop(columns=['TP_SEXO'])

In [200]:
train.head()

,CO_UF_RESIDENCIA,NU_IDADE,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,CO_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,...,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_REDACAO,M
0,11,31.0,0,1,1,32.0,1,10,1,1.0,...,1,1,426.5,487.4,530.9,415.3,1,1.0,680.0,0
1,31,23.0,1,3,1,31.0,1,3,1,NaN,...,1,1,463.0,452.3,456.6,407.2,0,1.0,520.0,0
2,31,17.0,0,3,1,31.0,2,0,2,1.0,...,1,1,381.7,474.4,530.6,622.8,0,1.0,600.0,1
3,25,16.0,1,1,1,25.0,3,0,1,NaN,...,1,1,426.7,343.9,444.2,507.0,1,1.0,660.0,1
4,23,19.0,1,1,1,23.0,1,1,1,NaN,...,1,1,623.7,609.1,637.1,805.3,0,1.0,840.0,1

# Trabalhando os NaNs do dataset:

Podemos observar as 10 colunas com mais dados faltantes.

In [76]:
train.isna().mean().reset_index(name="Dados faltantes").sort_values(by="Dados faltantes", ascending=False).head(10)

                     index  Dados faltantes
13      TP_LOCALIZACAO_ESC         0.774941
11               CO_UF_ESC         0.774941
14         TP_SIT_FUNC_ESC         0.774941
12  TP_DEPENDENCIA_ADM_ESC         0.774941
9                TP_ENSINO         0.435267
75              NU_NOTA_MT         0.271985
72              NU_NOTA_CN         0.271985
77       TP_STATUS_REDACAO         0.230176
78         NU_NOTA_REDACAO         0.230176
74              NU_NOTA_LC         0.230175

In [64]:
train_clean.groupby(by='TP_ENSINO').size()

TP_ENSINO
1.0    1861339
2.0       9015
dtype: int64

Pelo dicionario, a coluna TP_Ensino apresenta valor 1 como "não respondeu", logo, a quantidade de dados faltantes é absurdamente maior do que 43% como visto anteriormente.

In [88]:
train_clean=train.drop(columns=['CO_UF_ESC','TP_DEPENDENCIA_ADM_ESC','TP_SIT_FUNC_ESC','TP_LOCALIZACAO_ESC','TP_ENSINO'])
test_clean=test.drop(columns=['CO_UF_ESC','TP_DEPENDENCIA_ADM_ESC','TP_SIT_FUNC_ESC','TP_LOCALIZACAO_ESC','TP_ENSINO'])

In [89]:
train_clean.isna().mean().reset_index(name="Dados faltantes").sort_values(by="Dados faltantes", ascending=False).head(10)

                  index  Dados faltantes
70           NU_NOTA_MT         0.271985
67           NU_NOTA_CN         0.271985
73      NU_NOTA_REDACAO         0.230176
72    TP_STATUS_REDACAO         0.230176
69           NU_NOTA_LC         0.230175
68           NU_NOTA_CH         0.230175
5      CO_UF_NASCIMENTO         0.028552
1              NU_IDADE         0.000010
46  IN_MOBILIARIO_OBESO         0.000000
51           IN_SOROBAN         0.000000

In [90]:
train_clean.shape

(3311925, 75)

In [91]:
train_clean=train_clean.dropna()

In [92]:
train_clean.shape

(2336557, 75)

Foi perdido ~1/3 dos dados, podemos procurar uma maneira de minimizar isso posteriomente

# Ajustando a escala dos dados e dividindo as variaveis:

In [93]:
#Separando as variáveis dependentes e independentes do nosso modelo
Y_train = train_clean.loc[:,['NU_NOTA_CN','NU_NOTA_CH','NU_NOTA_LC','NU_NOTA_MT','NU_NOTA_REDACAO']]

X_train = train_clean.drop(columns=['NU_NOTA_CN','NU_NOTA_CH','NU_NOTA_LC','NU_NOTA_MT','NU_NOTA_REDACAO'])

In [96]:
X_train.shape
test_clean.shape

(2336557, 70)

(1783345, 71)

In [97]:
test_clean.head()

,NU_INSCRICAO,CO_UF_RESIDENCIA,NU_IDADE,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,CO_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,IN_NOME_SOCIAL,CO_MUNICIPIO_PROVA,CO_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,TP_LINGUA,TP_STATUS_REDACAO,M
0,5d5b362b-7388-4ac6-81b3-23573e4e2d3a,23,22.0,1,3,1,23.0,1,3,1,...,0,2305506,23,0,0,0,0,1,NaN,0
1,52356efd-3239-4cd2-a444-416625dfc560,35,19.0,1,1,1,35.0,1,1,1,...,0,3548500,35,1,1,1,1,0,1.0,0
2,1ba42e9a-dd61-4405-9b08-79b728ad23c9,35,16.0,1,1,1,35.0,3,0,1,...,0,3552106,35,1,1,1,1,1,1.0,0
3,16fa0f84-a88f-43e6-bcbb-8d5ea41e5f03,35,22.0,1,1,1,35.0,1,5,1,...,0,3541000,35,1,1,1,1,0,1.0,1
4,fa663d11-5052-4ab2-b771-3a3de3bdec55,41,17.0,1,1,1,41.0,2,0,3,...,0,4106902,41,1,1,1,1,0,1.0,1

In [98]:
test_INSCRICAO=test_clean.NU_INSCRICAO
test_clean=test_clean.drop(columns=['NU_INSCRICAO'])

MemoryError: Unable to allocate 898. MiB for an array with shape (66, 1783345) and data type int64

In [99]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)

X_test_scaled=scaler.transform(test_clean)

MemoryError: Unable to allocate 1.22 GiB for an array with shape (70, 2336557) and data type float64

In [207]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)

In [208]:
train_scaled.shape

(6, 70)

In [102]:
X_test_scaled = pd.DataFrame(X_test_scaled, columns=test_clean.columns)

In [103]:
X_test_scaled.head()

,CO_UF_RESIDENCIA,NU_IDADE,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,CO_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,...,IN_NOME_SOCIAL,CO_MUNICIPIO_PROVA,CO_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,TP_LINGUA,TP_STATUS_REDACAO,M
0,-0.123579,0.099504,0.707107,1.0,0.0,-1.054439,-0.654654,-0.132453,-0.447214,0.0,...,0.0,-0.128333,-0.123579,-1.0,-1.0,-1.0,-1.0,1.0,NaN,-1.0
1,1.655962,-0.497519,0.707107,-1.0,0.0,1.865546,-0.654654,-0.662266,-0.447214,0.0,...,0.0,1.692962,1.655962,0.0,0.0,0.0,0.0,-1.0,0.0,-1.0
2,1.655962,-1.094541,0.707107,-1.0,0.0,1.865546,1.963961,-0.927173,-0.447214,NaN,...,0.0,1.698246,1.655962,0.0,0.0,0.0,0.0,1.0,0.0,-1.0
3,1.655962,0.099504,0.707107,-1.0,0.0,1.865546,-0.654654,0.397360,-0.447214,0.0,...,0.0,1.681973,1.655962,0.0,0.0,0.0,0.0,-1.0,0.0,1.0
4,2.545733,-0.895533,0.707107,-1.0,0.0,3.325539,0.654654,-0.927173,4.919350,0.0,...,0.0,2.511160,2.545733,0.0,0.0,0.0,0.0,-1.0,0.0,1.0

In [209]:
X_train = sm.add_constant(X_train_scaled) 
model1 = sm.OLS(y1.astype(float), X_train.astype(float)).fit()
#model2 = sm.OLS(y2.astype(float), x.astype(float)).fit()
#model3 = sm.OLS(y3.astype(float), x.astype(float)).fit()
#model4 = sm.OLS(y4.astype(float), x.astype(float)).fit()
#model5 = sm.OLS(y5.astype(float), x.astype(float)).fit()

In [210]:
print(model1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             NU_NOTA_CN   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                    nan
Method:                 Least Squares   F-statistic:                       nan
Date:                Sat, 05 Feb 2022   Prob (F-statistic):                nan
Time:                        12:42:27   Log-Likelihood:                 165.23
No. Observations:                   6   AIC:                            -318.5
Df Residuals:                       0   BIC:                            -319.7
Df Model:                           5
Covariance Type:            nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
const                         467.1833        inf          0        nan         nan         nan
CO_UF_RESIDENCIA               -5.7490        inf         -0        nan         nan         nan
NU_IDADE                       -5.0856        inf         -0        nan         nan         nan
TP_ESTADO_CIVIL                21.0635        inf          0        nan         nan         nan
TP_COR_RACA                   -22.1076        inf         -0        nan         nan         nan
TP_NACIONALIDADE                     0        nan        nan        nan         nan         nan
CO_UF_NASCIMENTO              -27.5589        inf         -0        nan         nan         nan
TP_ST_CONCLUSAO               -28.3730        inf         -0        nan         nan         nan
TP_ANO_CONCLUIU                -9.8518        inf         -0        nan         nan         nan
TP_ESCOLA                     -17.1256        inf         -0        nan         nan         nan
IN_TREINEIRO                  -20.5108        inf         -0        nan         nan         nan
IN_BAIXA_VISAO                       0        nan        nan        nan         nan         nan
IN_CEGUEIRA                          0        nan        nan        nan         nan         nan
IN_SURDEZ                            0        nan        nan        nan         nan         nan
IN_DEFICIENCIA_AUDITIVA              0        nan        nan        nan         nan         nan
IN_SURDO_CEGUEIRA                    0        nan        nan        nan         nan         nan
IN_DEFICIENCIA_FISICA                0        nan        nan        nan         nan         nan
IN_DEFICIENCIA_MENTAL                0        nan        nan        nan         nan         nan
IN_DEFICIT_ATENCAO                   0        nan        nan        nan         nan         nan
IN_DISLEXIA                          0        nan        nan        nan         nan         nan
IN_DISCALCULIA                       0        nan        nan        nan         nan         nan
IN_AUTISMO                           0        nan        nan        nan         nan         nan
IN_VISAO_MONOCULAR                   0        nan        nan        nan         nan         nan
IN_OUTRA_DEF                         0        nan        nan        nan         nan         nan
IN_GESTANTE                          0        nan        nan        nan         nan         nan
IN_LACTANTE                          0        nan        nan        nan         nan         nan
IN_IDOSO                             0        nan        nan        nan         nan         nan
IN_ESTUDA_CLASSE_HOSPITALAR          0        nan        nan        nan         nan         nan
IN_SEM_RECURSO                       0        nan        nan        nan         nan         nan
IN_BRAILLE                           0        nan        nan        nan         nan         nan
IN_AMPLIADA_24                       0        nan        nan        nan         nan         nan
IN_AMPLIADA_18                       0        nan        nan        nan         nan         nan
IN_LEDOR                             0        nan        nan        nan         nan         nan
IN_ACESSO                            0        nan        nan        nan         nan         nan
IN_TRANSCRICAO                       0        nan        nan        nan         nan         nan
IN_LIBRAS                            0        nan        nan        nan         nan         nan
IN_TEMPO_ADICIONAL                   0        nan        nan        nan         nan         nan
IN_LEITURA_LABIAL                    0        nan        nan        nan         nan         nan
IN_MESA_CADEIRA_RODAS                0        nan        nan        nan         nan         nan
IN_MESA_CADEIRA_SEPARADA             0        nan        nan        nan         nan         nan
IN_APOIO_PERNA                       0        nan        nan        nan         nan         nan
IN_GUIA_INTERPRETE                   0        nan        nan        nan         nan         nan
IN_COMPUTADOR                        0        nan        nan        nan         nan         nan
IN_CADEIRA_ESPECIAL                  0        nan        nan        nan         nan         nan
IN_CADEIRA_CANHOTO                   0        nan        nan        nan         nan         nan
IN_CADEIRA_ACOLCHOADA                0        nan        nan        nan         nan         nan
IN_PROVA_DEITADO                     0        nan        nan        nan         nan         nan
IN_MOBILIARIO_OBESO                  0        nan        nan        nan         nan         nan
IN_LAMINA_OVERLAY                    0        nan        nan        nan         nan         nan
IN_PROTETOR_AURICULAR                0        nan        nan        nan         nan         nan
IN_MEDIDOR_GLICOSE                   0        nan        nan        nan         nan         nan
IN_MAQUINA_BRAILE                    0        nan        nan        nan         nan         nan
IN_SOROBAN                           0        nan        nan        nan         nan         nan
IN_MARCA_PASSO                       0        nan        nan        nan         nan         nan
IN_SONDA                             0        nan        nan        nan         nan         nan
IN_MEDICAMENTOS                      0        nan        nan        nan         nan         nan
IN_SALA_INDIVIDUAL                   0        nan        nan        nan         nan         nan
IN_SALA_ESPECIAL                     0        nan        nan        nan         nan         nan
IN_SALA_ACOMPANHANTE                 0        nan        nan        nan         nan         nan
IN_MOBILIARIO_ESPECIFICO             0        nan        nan        nan         nan         nan
IN_MATERIAL_ESPECIFICO               0        nan        nan        nan         nan         nan
IN_NOME_SOCIAL                       0        nan        nan        nan         nan         nan
CO_MUNICIPIO_PROVA             -6.0041        inf         -0        nan         nan         nan
CO_UF_PROVA                    -5.7490        inf         -0        nan         nan         nan
TP_PRESENCA_CN                       0        nan        nan        nan         nan         nan
TP_PRESENCA_CH                       0        nan        nan        nan         nan         nan
TP_PRESENCA_LC                       0        nan        nan        nan         nan         nan
TP_PRESENCA_MT                       0        nan        nan        nan         nan         nan
TP_LINGUA                     -27.3567        inf         -0        nan         nan         nan
TP_STATUS_REDACAO                    0        nan        nan        nan         nan         nan
M                              16.4372        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   3.221
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.533
Skew:                           0.726   Prob(JB):                        0.766
Kurtosis:                       2.848   Cond. No.                         3.04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1728: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1728: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1650: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\base\model.py:1452: RuntimeWarning: invalid value encountered in multiply
  cov_p = self.normalized_cov_params * scale

In [ ]:
print(model2.summary())

In [ ]:
print(model3.summary())

In [ ]:
print(model4.summary())

In [ ]:
print(model5.summary())

In [ ]:
#predições
x_test = sm.add_constant(test_clean)
y_pred =  model1.predict(x_test) # predict out of sample
print(y_pred)

In [ ]:
#predições
x_test = sm.add_constant(test_clean)
y_pred2 =  model2.predict(x_test) # predict out of sample
print(y_pred2)

In [ ]:
#predições
x_test = sm.add_constant(test_clean)
y_pred3 =  model3.predict(x_test) # predict out of sample
print(y_pred3)

In [ ]:
#predições
x_test = sm.add_constant(test_clean)
y_pred4 =  model4.predict(x_test) # predict out of sample
print(y_pred4)

In [ ]:
#predições
x_test = sm.add_constant(test_clean)
y_pred5 =  model5.predict(x_test) # predict out of sample
print(y_pred5)

In [35]:
quests ={ 
    'A': 1,
    'B': 2,
    'C': 3,
    'D': 4,
    'E': 5,
    'F': 6 
}